# Generated by Django 5.2.1 on 2025-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr_app', '0002_table_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
