# Generated by Django 5.2.1 on 2025-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr_app', '0004_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/ADMIN/Desktop/site_de_restauration/sdr/'),
        ),
    ]
