# Generated by Django 5.2.1 on 2025-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr_app', '0005_alter_plat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
