# Generated by Django 5.2.1 on 2025-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr_app', '0006_alter_plat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('admin', 'administrateur')], default='client', max_length=10),
        ),
    ]
