# Generated by Django 5.2.1 on 2025-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdr_app', '0007_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'administrateur')], default='client', max_length=10),
        ),
    ]
